### ISSUE TITLE
Remove dead PHP code in API server

### ISSUE THREAD

**Issue by krivard** [cmu-delphi/delphi-epidata#781] opened 2021-12-09 16:08 UTC
We've still got [PHP code kicking around in the server](https://github.com/cmu-delphi/delphi-epidata/tree/dev/src/server) but it's not being used anywhere. We should get rid of it so new folks to the project don't get confused.

* api.php
* api_helpers.php
* database_config.php

**Comment by melange396** [comment] 2022-12-06 14:57
duplicate of #1001

**Closed by melange396** 2022-12-06 14:57 UTC
Labels: chore
