### ISSUE TITLE
FluView data missing from epiweek 202235 onward

### ISSUE THREAD

**Issue by filipj8** [cmu-delphi/delphi-epidata#1036] opened 2022-11-18 18:10 UTC
When I query the FluView API, it's only pulling data up to epiweek 202235 (it's currently epiweek 202246).

```python
from delphi_epidata import Epidata

Epidata.fluview('nat', {'from': '202234', 'to': '202245'})

# result
{'epidata': [{'release_date': '2022-09-09',
   'region': 'nat',
   'issue': 202235,
   'epiweek': 202234,
   'lag': 1,
   'num_ili': 34559,
   'num_patients': 1907135,
   'num_providers': 3192,
   'num_age_0': 10455,
   'num_age_1': 12164,
   'num_age_2': None,
   'num_age_3': 6829,
   'num_age_4': 2634,
   'num_age_5': 2477,
   'wili': 1.79585,
   'ili': 1.81209},
  {'release_date': '2022-09-09',
   'region': 'nat',
   'issue': 202235,
   'epiweek': 202235,
   'lag': 0,
   'num_ili': 34077,
   'num_patients': 1843641,
   'num_providers': 3030,
   'num_age_0': 10586,
   'num_age_1': 12513,
   'num_age_2': None,
   'num_age_3': 6346,
   'num_age_4': 2422,
   'num_age_5': 2210,
   'wili': 1.86118,
   'ili': 1.84835}],
 'result': 1,
 'message': 'success'}
```

Visiting the URL directly:

https://delphi.cmu.edu/epidata/fluview/?regions=nat&epiweeks=202236
```python
{ "epidata": [], "result": -2, "message": "no results" }
```

**Comment by krivard** [comment] 2022-11-18 18:53
Duplicate of #993, but thankyou for reporting!

**Closed by krivard** 2022-11-18 18:53 UTC

**Comment by dmytrotsko** [comment] 2023-06-29 13:49
@filipj8 Hey, this issue has been resolved. Thank you for reporting once again!
