### ISSUE TITLE
Update CI for set-output and save-state

### ISSUE THREAD

**Issue by krivard** [cmu-delphi/delphi-epidata#1033] opened 2022-11-17 18:14 UTC
We're generating these messages in builds:

> The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

> The `save-state` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

**Comment by melange396** [comment] 2023-02-03 17:27
duplicate of #1015

**Closed by melange396** 2023-02-03 17:27 UTC
Labels: chore
